@startuml "(ACD-06) Negosiasi Kontrak"
!include ../../activity-config.puml
!include ../../theme.puml
title "Negosiasi Kontrak"
footer "version 1.0"
|Owner|
|Sistem|
|Tenant|
start
:Mendapatkan Notifikasi\nKontrak Sudah Dibuat;
:Review Isi Kontrak;
:Terima/Reject Kontrak;
if (Kontrak Diterima?) then (Tidak)
    |Sistem|
    :Update Status Kontrak;
    note right
        **(DB)** rentals table
        status: rejected
    end note
    (A)
    detach
    |Tenant|
    (A)
    :Mengajukan Negosiasi;
    if (Negosiasi?) then (Tidak)
        |Sistem|
        :Membatalkan Permintaan Sewa;
        :Update Data Sewa;
        note right
            **(DB)** rentals table
            status: tenant_rejected
        end note
        stop
    else (Ya)
        |Tenant|
        :Mengisi Form Negosiasi;
        note left
            **Data**:
            Bagian Kontrak yang Ingin Diubah,
            Alasan Perubahan
        end note
        |Sistem|
        :Update Data Sewa;
        note right
            **(DB)** rentals table
            status: renegotiated
        end note
        |Owner|
        :Review Permintaan Negosiasi;
        :Respons Permintaan Negosiasi;
        if (Permintaan Negosiasi Diterima?) then (Ya)
            :Kembali Ke Tahap Membuat Kontrak;
        else (Tidak)
            |Sistem|
            (A)
            detach
        endif
        |Owner|
        stop
    endif
else (Ya)
    |Sistem|
    :Simpan Status Kontrak Diterima;
    note right
        **(DB)** rentals table
        status: tenants_accepted
    end note
    |Owner|
    :Mendapatkan Notifikasi\nKontrak Diterima;
    :Lanjut ke TTD Kontrak;
    stop
endif
@enduml