@startuml "(C4D-03) Component Diagram - Backend Container"
' !include <C4/C4_Container>
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
footer "version 1.0"
System_Boundary(houseRental, "House Rental System", "Software System") {
    Container(website, "UI", "Web interface for tenants and renters", $techn="React SPA")
    Container_Boundary(backend, "Backend") {
        Component(authController, "Auth Controller", "Handles user authentication and authorization", $techn="REST Controller")
        Component(userController, "User Controller", "Handles user-related operations", $techn="REST Controller")
        Component(rentalController, "Rental Controller", "Handles rental related operations", $techn="REST Controller")
        Component(propertyController, "Property Controller", "Handles property related operations", $techn="REST Controller")
        Component(paymentController, "Payment Controller", "Handles payment processing", $techn="REST Controller")
        Component(authService, "Auth Service", "Contains the business logic for user authentication, token generation, and password management", $techn="Node.js Service")
        Component(userService, "User Service", "Implements the core logic for managing user data", $techn="Node.js Service")
        Component(propertyService, "Property Service", "Implements the core logic for managing property data", $techn="Node.js Service")
    }
    ContainerDb(database, "Database", "Stores user and rental related data", $techn="MySQL")
    ContainerDb(objectStorage, "Object Storage", "Stores documents and images", $techn="Vercel Blob")
}
Rel(website, backend, "Calls API to", "HTTPS")

@enduml