@startuml "(UCD-01) House Rental System"
'====================== Metadata ======================
!include ../../theme.puml
left to right direction
title Use Case Diagram
footer version 1.1
'====================== Metadata ======================

'NOTE: Karena setting l to r, arah jadi berubah
' left <-> up
' right <-> down

'======================= Actor =======================
actor Tenant
' actor User
actor Owner
' User <|- Owner
' User <|- Tenant
'======================= Actor =======================

'====================== Usecase ======================
rectangle Sistem {
    usecase (Register) as register
    usecase (Login) as login
    usecase (Reset\nPassword) as resetPassword
    usecase (Mencari & Melihat\nProperti) as cariLihatProperti
    usecase (Mengatur Properti) as manageProperti
    usecase (Menyewa Properti) as sewaProperti
    usecase (Memperpanjang Kontrak) as perpanjangKontrak
    usecase (Melakukan\nPembayaran) as bayar
    usecase (Mengajukan Sewa) as mengajukanSewa
    usecase (Mengelola Pengajuan\nSewa) as kelolaPengajuanSewa
    usecase (Negosiasi Kontrak Sewa) as negoisasiKontrak
    usecase (Chat) as chat
    usecase (Mengakhiri Kontrak\nLebih Awal) as akhiriKontrak
    usecase (Sign Dokumen Kontrak) as signDokumenKontrak
}
'====================== Usecase ======================

'================ Connection & Layout ================
Tenant ---> cariLihatProperti
cariLihatProperti <. chat : <<extends>>

Tenant -> sewaProperti
' sewaProperti ..> ttdKontrak : <<include>>
sewaProperti ..> bayar : <<include>>
sewaProperti ..> mengajukanSewa : <<include>>
sewaProperti ..> negoisasiKontrak : <<include>>
negoisasiKontrak <. signDokumenKontrak : <<extends>>
Tenant -> perpanjangKontrak
' perpanjangKontrak ..> bayar : <<include>>
Tenant -> akhiriKontrak

Owner -up-> manageProperti
Owner -up-> negoisasiKontrak
Owner -up-> kelolaPengajuanSewa

Tenant -> register
Owner -up-> register
Tenant -> login
Owner -up-> login
Tenant -> resetPassword
Owner -up-> resetPassword
' Tenant -> chat
Owner -up-> chat

' Tenant
'================ Connection & Layout ================



'====================== Alignment ======================
' Sistem -- Owner
'====================== Alignment ======================
@enduml